export const SET_USER_VERIFIED = 'SET_USER_VERIFIED';
export const SET_EMAIL_VERIFICATION = 'SET_EMAIL_VERIFICATION';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const SET_TOAST = 'SET_TOAST';
export const SET_TOAST_TITLE = 'SET_TOAST_TITLE';
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';
export const SET_TOAST_TYPE = 'SET_TOAST_TYPE';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_RESULT = 'SET_RESULT';
export const SET_KEYWORD = 'SET_KEYWORD';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';


export const SET_NOTIFICATIONS_OPEN = 'SET_NOTIFICATIONS_OPEN';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

export const SET_SEARCH_VOLUME_HISTORY = 'SET_SEARCH_VOLUME_HISTORY';





