export const SET_KEYWORD = 'SET_KEYWORD';
export const SET_RESULT = 'SET_RESULT';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_SEARCH_VOLUME_HISTORY = 'SET_SEARCH_VOLUME_HISTORY';
