export const SET_LOOKUP_SELECTED = 'SET_LOOKUP_SELECTED';
export const SET_LOOKUP_UNSELECTED = 'SET_LOOKUP_UNSELECTED';
export const DELETE_LOOKUP = 'DELETE_LOOKUP';
export const SET_LOOKUPS = 'SET_LOOKUPS';